### ISSUE TITLE
Provide schemas and generated java object model in maven central

### ISSUE THREAD

**Issue by rhoegg** [XeroAPI/XeroAPI-Schemas#47]
It would make it easier to use these schemas and the generated classes for java developers if we could just add a dependency on your official JAR in maven central.  Any plans to release it that way?

**Comment by SidneyAllen** [comment]
Hi @rhoegg 

Thanks for the suggestion - I'm a bit new to generating Maven Artifacts, so instead of deploying to a Maven Central Repository - I'm serving the Maven Artifact from a branch of this github repo.  I've tested it and appears to work well.  Look forward to feedback on this approach.  See the README for how to add this dependency to your POM file
